Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -4,6 +4,20 @@ trigger:
 pool:
   vmImage: ubuntu-latest
 
+parameters:
+- name: appName
+  default: ''
+- name: projectName
+  default: ''
+- name: scanTypeList
+  type: string
+  default: "SCA,SAST"
+  # Allowed values: Comma-separated list containing any of: SCA,SAST,IMAGE,ALL
+- name: imagesToScan
+  default: ''
+- name: postScanSCAReports
+  default: ''
+
 variables:
 - name: MEND_URL
   value: https://app-eu.whitesourcesoftware.com
@@ -14,12 +28,6 @@ variables:
   value: https://app-eu.whitesourcesoftware.com
 - name: MEND_SCA_API_URL
   value: https://api-app-eu.whitesourcesoftware.com/api/v2.0
-- name: MEND_SCA_EMAIL
-  value: $(MEND_SCA_EMAIL)
-- name: MEND_SCA_USER_KEY
-  value: $(MEND_SCA_USER_KEY)
-- name: MEND_SCA_ORG_UUID
-  value: $(MEND_SCA_ORG_UUID)
 - name: MEND_LOG_LEVEL
   value: DEBUG
 
@@ -40,45 +48,87 @@ steps:
       sudo mv composer.phar /usr/local/bin/composer
     displayName: 'Install dependencies including PHP package manager'
 
-  # Download Mend CLI with recommended command
+  # Check and Install Mend CLI if not present
   - script: |
-      sudo curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && sudo chmod +x /usr/local/bin/mend
-    displayName: 'Download and set up Mend CLI'
-
-  # Authenticate with Mend CLI
-  - script: |
-      mend auth login --non-interactive --env $MEND_SCA_ENV
-    env:
-      MEND_SCA_URL: $(MEND_SCA_URL)
-      MEND_SCA_EMAIL: $(MEND_SCA_EMAIL)
-      MEND_SCA_USER_KEY: $(MEND_SCA_USER_KEY)
-      MEND_SCA_ORG_UUID: $(MEND_SCA_ORG_UUID)
-      MEND_SCA_API_URL: $(MEND_SCA_API_URL)
-      MEND_LOG_LEVEL: $(MEND_LOG_LEVEL)
-    displayName: 'Authenticate with Mend CLI'
-
-  # Install project dependencies using Composer
-  - script: |
-      composer install
-    displayName: 'Install PHP dependencies'
-
-  # Run Mend SCA CLI to scan the project
-  - script: |
-      echo Running Mend SCA scan
-      mend dep -u -s "Ruby-Platform//CLIAzure//PHPazure" --fail-policy --non-interactive --export-results dep-results.txt
-      export dep_exit=$?
-      if [[ "$dep_exit" == "9" ]]; then
-        echo "##vso[task.logissue type=warning;] Dependency scan policy violation"
-        echo "##vso[task.complete result=SucceededWithIssues;]"
-      else
-        echo "No policy violations found in dependencies scan"
+      mend -h > /dev/null 2>&1
+      if [ $? -eq 127 ]; then
+        echo "Downloading Mend CLI"
+        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
       fi
-      echo "##vso[task.uploadsummary]$(System.DefaultWorkingDirectory)/dep-results.txt"
+    displayName: 'Check and Install Mend CLI'
+
+  # Run Mend CLI Scans based on parameters
+  - script: |
+      WS_SCAN_TYPES="${{ parameters.scanTypeList }}"
+
+      ### Mend SCA Scan #######
+      if [[ "$WS_SCAN_TYPES" == *"SCA"* || "$WS_SCAN_TYPES" == *"ALL"* ]];
+      then
+        echo Running Mend SCA scan
+        mend dep -u -s *//${{ parameters.appName }}//${{ parameters.projectName }} --fail-policy --non-interactive --export-results dep-results.txt
+        export dep_exit=$?
+        if [[ "$dep_exit" == "9" ]]; then
+          echo "##vso[task.logissue type=warning;] Dependency scan policy violation"
+          echo "##vso[task.complete result=SucceededWithIssues;]"
+        else
+          echo "No policy violations found in dependencies scan"
+        fi
+        echo "##vso[task.uploadsummary]$(System.DefaultWorkingDirectory)/dep-results.txt"
+      fi
+      #########################
+
+      ### Mend SAST Scan ######
+      if [[ "$WS_SCAN_TYPES" == *"SAST"* || "$WS_SCAN_TYPES" == *"ALL"* ]];
+      then
+        echo Running Mend SAST scan
+        mend code -s *//${{ parameters.appName }}//${{ parameters.projectName }} -r --formats sarif --filename code-results --non-interactive
+        export code_exit=$?
+        if [[ "$code_exit" == "9" ]]; then
+          echo "##vso[task.logissue type=warning;] Code scan threshold violation"
+          echo "##vso[task.complete result=SucceededWithIssues;]"
+        else
+          echo "No policy violations found in code scan"
+        fi
+        echo "##vso[task.setvariable variable=publishLogs]Yes"
+      fi
+      #########################
+
+      ### Mend IMAGE Scan ######
+      if [[ "$WS_SCAN_TYPES" == *"IMAGE"* || "$WS_SCAN_TYPES" == *"ALL"* ]];
+      then
+        echo Running Mend Image scan
+        echo "Showing images that will be scanned"
+        cat ${{ parameters.imagesToScan }}
+        file="${{ parameters.imagesToScan }}"
+        while IFS= read -r line
+        do
+          slashline=$(echo "$line" | sed 's/\//-/g')
+          escline=$(echo "$slashline" | sed 's/:/_/')
+          echo "Scanning the image named $line with friendly name of $escline"
+          mend image $line -s *//${{ parameters.appName }}//${{ parameters.projectName }} --filter critical --fail-policy > $escline-results.txt
+          image_exit=$?
+          if [[ "$image_exit" == "9" ]]; then
+            echo "##vso[task.logissue type=warning;] Image scan policy violation in $escline"
+            echo "##vso[task.complete result=SucceededWithIssues;]"
+          else
+            echo "No policy violations found in $line scan"
+          fi
+          cat $escline-results.txt
+          echo "##vso[task.uploadsummary]$(System.DefaultWorkingDirectory)/${escline}-results.txt"
+        done < "$file"
+      fi
+      #########################
+
+      ### Moving Mend logs ###
+      mv ~/.mend/logs $(System.DefaultWorkingDirectory)
+      mv *results* $(System.DefaultWorkingDirectory)/logs/
+      #########################
     env:
       MEND_SCA_URL: $(MEND_SCA_URL)
-      MEND_SCA_EMAIL: $(MEND_SCA_EMAIL)
-      MEND_SCA_USER_KEY: $(MEND_SCA_USER_KEY)
-      MEND_SCA_ORG_UUID: $(MEND_SCA_ORG_UUID)
+      MEND_SCA_EMAIL: $(MEND_SCA_EMAIL_SECRET)
+      MEND_SCA_USER_KEY: $(MEND_SCA_USER_KEY_SECRET)
+      MEND_SCA_ORG_UUID: $(MEND_SCA_ORG_UUID_SECRET)
       MEND_SCA_API_URL: $(MEND_SCA_API_URL)
       MEND_LOG_LEVEL: $(MEND_LOG_LEVEL)
-    displayName: 'Run Mend SCA CLI scan'
+    displayName: 'Mend CLI Scan'
+
